language: go

go:
  - 1.8

env:
  - "MY_GOOS=linux MY_GOARCH=amd64"
  - "MY_GOOS=darwin MY_GOARCH=amd64"
  - "MY_GOOS=windows MY_GOARCH=amd64"
  - "MY_GOOS=windows MY_GOARCH=386"

before_install:
  - "test $MY_GOOS.$MY_GOARCH != linux.amd64 || go get github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/pierrre/gotestcover"

install:
  - "go get github.com/taskcluster/livelog"
  - "go get github.com/gordonklaus/ineffassign"

script:
  - export GOOS=linux
  - export GOARCH=amd64
  - "go get ./gw-codegen"
  - "go generate"
  - "export GOOS=${MY_GOOS}"
  - "export GOARCH=${MY_GOARCH}"
  - "test $(git status --porcelain | wc -l) == 0"
  - "go get -v -t ./..."
  - "if test $GOOS.$GOARCH = linux.amd64; then GORACE=history_size=7 ${GOPATH}/bin/gotestcover -v -coverprofile=coverage.report -race -timeout 1h ./... && go tool cover -func=coverage.report; fi"
  - "test $GOOS.$GOARCH != linux.amd64 || ${GOPATH}/bin/ineffassign ."

after_script:
  - "test $MY_GOOS.$MY_GOARCH != linux.amd64 || ${GOPATH}/bin/goveralls -coverprofile=coverage.report -service=travis-ci"

before_deploy:
  - "source .travis_rename_releases.sh"

deploy:
  api_key:
    secure: KuifEWzfB5C9GFHMjFpSpbHWLN9cs/1afRuJhP4aADU3i55zb0QDzIu6+aGLlL0jsV5T07AqgPvJm4bOQNnWVhlhyHStrkIdzUpCtiCVNnPH3cYUkJ4/0zJyJaopnZfuX/2m2F+ajNC2Z94mxuu4qUUgqFO9x708xy0LYCofTEU=
  file:
    - "${RELEASE_FILE}"
  provider: releases
  skip_cleanup: true
  on:
    repo: taskcluster/generic-worker
    tags: true

notifications:
  irc:
    channels:
      - "irc.mozilla.org#taskcluster-bots"
    on_failure: always
    on_success: change
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
