language: go

go:
  # this is a lie - we will use 1.7 which isn't supported yet
  # by downloading it later in "before_install" section
  # we use 1.7 due to https://github.com/contester/runlib/issues/5#issuecomment-241419381
  # which could have also been achieved via vendoring an older version, but for let's
  # keep up-to-date with latest version
  - 1.6

env:
  - "MY_GOOS=linux MY_GOARCH=amd64"
  - "MY_GOOS=darwin MY_GOARCH=amd64"
  - "MY_GOOS=windows MY_GOARCH=amd64"
  - "MY_GOOS=windows MY_GOARCH=386"

before_install:
  - curl -o go.tar.gz -sL https://storage.googleapis.com/golang/go1.7.5.linux-amd64.tar.gz
  - tar -C $HOME -xf go.tar.gz
  - rm go.tar.gz
  - export GOROOT="${HOME}/go"
  - export PATH="${GOROOT}/bin:${PATH}"
  - export GOOS="${MY_GOOS}"
  - export GOARCH="${MY_GOARCH}"
  - go version
  - go env
  - "test $GOOS.$GOARCH != linux.amd64 || go get github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/pierrre/gotestcover"

install:
  - "go get github.com/taskcluster/livelog"
  - "go get github.com/gordonklaus/ineffassign"

script:
  - export GOOS=linux
  - export GOARCH=amd64
  - "go get ./gw-codegen"
  - "go generate"
  - "export GOOS=${MY_GOOS}"
  - "export GOARCH=${MY_GOARCH}"
  - "test $(git status --porcelain | wc -l) == 0"
  - "go get -v -t ./..."
  - "if test $GOOS.$GOARCH = linux.amd64; then GORACE=history_size=7 travis_wait 30 ${GOPATH}/bin/gotestcover -v -coverprofile=coverage.report -race -timeout 1h ./... && go tool cover -func=coverage.report; fi"
  - "test $GOOS.$GOARCH != linux.amd64 || ${GOPATH}/bin/ineffassign ."

after_script:
  - "test $GOOS.$GOARCH != linux.amd64 || ${GOPATH}/bin/goveralls -coverprofile=coverage.report -service=travis-ci"

before_deploy:
  - "source .travis_rename_releases.sh"

deploy:
  api_key:
    secure: KuifEWzfB5C9GFHMjFpSpbHWLN9cs/1afRuJhP4aADU3i55zb0QDzIu6+aGLlL0jsV5T07AqgPvJm4bOQNnWVhlhyHStrkIdzUpCtiCVNnPH3cYUkJ4/0zJyJaopnZfuX/2m2F+ajNC2Z94mxuu4qUUgqFO9x708xy0LYCofTEU=
  file:
    - "${RELEASE_FILE}"
  provider: releases
  skip_cleanup: true
  on:
    repo: taskcluster/generic-worker
    tags: true

notifications:
  irc:
    channels:
      - "irc.mozilla.org#taskcluster-bots"
    on_failure: always
    on_success: change
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
