version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\taskcluster\generic-worker

environment:
  GOPATH: c:\gopath
  CGO_ENABLED: 1
  TASKCLUSTER_CLIENT_ID: project/taskcluster/generic-worker/appveyor-ci
  TASKCLUSTER_ACCESS_TOKEN:
    secure: y6boO7fth23zAJI91z4utmcYizD6nlbN/pLLtPiJOZb8n/Vrv+SUz6wkO9xWzmS0
  PULSE_USERNAME: appveyor_generic-worker
  PULSE_PASSWORD:
    secure: amqPDn3RampnxBJxMp2aFxssvaDT6BYh/nt7HYXuhDQ=


install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.7.1.windows-amd64.zip
  - 7z x go1.7.1.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - go get github.com/taskcluster/livelog
  - go get ./gw-codegen
  - set PATH=%GOPATH%\bin;%PATH%
  - go generate
  - go get -v -t ./...
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/golang/lint/golint

build: off

test_script:
  - go vet ./...
  - GORACE=history_size=7 go test -v -race -timeout 1h ./...
  - ineffassign .

after_test:
  - golint ./...

deploy: off
